[package]
name = "databases"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
dotenv = "0.15.0"
futures = "0.3.31"
sqlx = {version = "0.8.6", features =["runtime-tokio-native-tls", "sqlite"]}
tokio = { version = "1.46.0", features = ["full"] }
