[package]
name = "network-service-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "1.3.3", features = ["i128"]}
crc32fast = "1.4.2"
serde = { version = "1.0.219", features = ["derive"] }
